from django.urls import path

from tasks.views import (
    index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ProjectListView,
    ProjectDetailView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectCreateView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    SendTaskToReview,
    ApproveTask,
    AddAssignee,
    RemoveAssignee,
    AddTaskToProject,
    RemoveTaskFromProject,
    TeamRemoveProject,
    ToggleAssignToTeam,
    AddProjectToTeam,
)

urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tasktypes/",
        TaskTypeListView.as_view(),
        name="task_type-list",
    ),
    path(
        "tasktypes/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task_type-update",
    ),
    path(
        "tasktypes/create/",
        TaskTypeCreateView.as_view(),
        name="task_type-create",
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/<int:pk>/send-review/",
        SendTaskToReview.as_view(),
        name="send_to_review"
    ),
    path(
        "tasks/<int:pk>/approve/",
        ApproveTask.as_view(),
        name="approve"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tasks/<int:pk>/add-assignee/",
        AddAssignee.as_view(),
        name="add-assignee",
    ),
    path(
        "tasks/<int:pk>/remove-assignee/<int:user_id>/",
        RemoveAssignee.as_view(),
        name="remove-assignee",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list",
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "projects/<int:pk>/add-task/",
        AddTaskToProject.as_view(),
        name="project-add-task",
    ),
    path(
        "projects/<int:pk>/remove-task/<int:task_id>/",
        RemoveTaskFromProject.as_view(),
        name="project-remove-task",
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list",
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "teams/",
        TeamListView.as_view(),
        name="team-list",
    ),
    path(
        "teams/<int:pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update",
    ),
    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create",
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete",
    ),
    path(
        "teams/<int:pk>/remove-project/<int:project_id>/",
        TeamRemoveProject.as_view(),
        name="team-remove-project",
    ),
    path(
        "teams/<int:pk>/toggle-assign/",
        ToggleAssignToTeam.as_view(),
        name="toggle-team-assign",
    ),
    path(
        "teams/<int:pk>/add-project/",
        AddProjectToTeam.as_view(),
        name="team-add-project",
    ),
]

app_name = "tasks"
